#!/usr/bin/python
# -*- coding: utf-8 -*-

"""
Litterae is a PyQt4 application designed to help researchers
track, organise and read papers of ArXiV.
"""

from src.main import main

if __name__ == "__main__":
    main()
