#!/usr/bin/python2.7
# -*- coding: utf-8 -*-

"""
Litterae - a PyQt4 application designed to help researchers manage papers

Credits
'----> Code - Matthew Withers - @amattwithers
'----> App Icon - Christoph Laier - plus.google.com/+ChristophLaier
'----> UI Icons - OpenIconic (read licence at img/ui/ICON-LICENSE)

This software is licensed under GPLv2 - please see bundled LICENSE file

Copyright Matthew Withers 2015
"""

from src.main import main

import signal
signal.signal(signal.SIGINT, signal.SIG_DFL)

if __name__ == "__main__":
    main()
